apiVersion: v1
kind: Pod
metadata:
  name: bootpod
  labels:
    app: idssapp 
spec:
  containers:
    - name: idss
      image: ghcr.io/pulihub/idss:latest
      imagePullPolicy: Always
      env:
        - name: IDSS_PORT
          value: "19000"
        - name: IDSS_NR
          value: "10"
---
apiVersion: v1
kind: Pod
metadata:
  name: nodepod
  labels:
    app: idssapp 
spec:
  containers:
    - name: idss
      image: ghcr.io/pulihub/idss:latest
      imagePullPolicy: Always
      env:
        - name: IDSS_BOOTSTRAP_IP
          value: "10.244.2.11"
        - name: IDSS_PORT
          value: "19000"
        - name: IDSS_NR
          value: "10"

