
apiVersion: v1
kind: Pod
metadata:
  name: nodepod
  labels:
    app: idssapp 
spec:
  containers:
    - name: idss
      image: ghcr.io/pulihub/idss:latest
      imagePullPolicy: Always
      env:
        - name: IDSS_BOOTSTRAP_IP
          value: "10.10.5.20"
        - name: IDSS_PORT
          value: "19000"
        - name: IDSS_NR
          value: "10"
      volumeMounts:
        - name: cert
          mountPath: "/certs"
          readOnly: true
  volumes:
    - name: cert
      secret:
        secretName: idsscerts
