apiVersion: v1
kind: Service
metadata:
  name: idss-nodes
spec:
  clusterIP: None # Headless Service
  selector:
    app: idssnode
  ports:
    - protocol: UDP
      port: 19001
      targetPort: 19001
      name: p2p-port 
    - protocol: TCP
      port: 19000
      targetPort: 19000
      name: idss-port
---
apiVersion: apps/v1
kind: StatefulSet # <-- Cambiato da Deployment a StatefulSet
metadata:
  name: idssnode
  labels:
    app: idssnode
spec:
  serviceName: "idss-nodes" # <-- FONDAMENTALE: Collega i Pod al DNS dell'Headless Service
  replicas: 2
  selector:
    matchLabels:
      app: idssnode
  template:
    metadata:
      labels:
        app: idssnode
    spec:
      containers:
      - name: idssnode
        image: ghcr.io/pulihub/idss:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 19000
          protocol: TCP
        - containerPort: 19001
          protocol: UDP
        volumeMounts:
        - name: cert
          mountPath: "/certs"
          readOnly: true
        env:
        - name: IDSS_PORT
          value: "19000"
        - name: IDSS_NR
          value: "10"
        - name: IDSS_BOOTSTRAP_IP
          value: "idss-bootstrap" # Punta al servizio del bootstrap
      volumes:
      - name: cert
        secret:
          secretName: idsscerts
